services:

  # JUPYTER
  automl:
    image: mfeurer/auto-sklearn:master
    volumes:
    - ${PWD}/ml:/opt/nb
    ports:
    - 8789:8888
    networks:
      - app_net
    command: 
    - mkdir -p /opt/nb 
    - jupyter notebook --notebook-dir=/opt/nb --ip='0.0.0.0' --port=8888 --no-browser --allow-root"
