  # CURSO DATABASE : exemplo MySQL
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: mysqldb
      PMA_PORT: 3366
      PMA_ARBITRARY: 1
      PMA_USER: admin
      PMA_PASSWORD: admin
    ports:
      - 8082:80  
    depends_on: 
      - mysqldb
    
  mysqldb:
    #image: mysql:5.7 # bd vazio, sobe mais rapido
    image: tonanuvem/mysql:curso_db # bd com a tabela curso
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: fiap
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    ports:
      - "3366:3306"
    volumes:
      - mysqldata:/var/lib/mysql
