services:
  mlflow:
    image: docker.io/bitnami/mlflow:latest
    ports:
      - "5000:5000"
    networks:
      - app_net
    environment:
      - MLFLOW_TRACKING_URI=postgresql://mlflow_db:5432/mlflow
      - MLFLOW_S3_ENDPOINT_URL=http://minio:9000
      - AWS_ACCESS_KEY_ID=fiap
      - AWS_SECRET_ACCESS_KEY=fiap
      - MLFLOW_ARTIFACT_ROOT=s3://mlflow-artifacts
      - MLFLOW_SERVER_HOST=0.0.0.0
    depends_on:
      - mlflow_db
      - minio
    #command: ["mlflow", "server", "--host", "0.0.0.0", "--port", "5000"]

  mlflow_db:
    image: docker.io/bitnami/postgresql:latest
    networks:
      - app_net
    environment:
      - POSTGRESQL_USERNAME=mlflow
      - POSTGRESQL_PASSWORD=mlflow123
      - POSTGRESQL_DATABASE=mlflow
      
  minio:
    image: docker.io/bitnami/minio:latest
    ports:
      - "9000:9000"
    networks:
      - app_net
    environment:
      - MINIO_ROOT_USER=fiap
      - MINIO_ROOT_PASSWORD=fiap

networks:
  app_net:
    external: true
