    services:
      mlflow:
        image: docker.io/bitnami/mlflow:latest
        ports:
          - "5000:5000"
        environment:
          - MLFLOW_TRACKING_URI=postgresql://mlflow_db:5432/mlflow
          - MLFLOW_S3_ENDPOINT_URL=http://minio:9000
          - AWS_ACCESS_KEY_ID=minio
          - AWS_SECRET_ACCESS_KEY=minio123
          - MLFLOW_ARTIFACT_ROOT=s3://mlflow-artifacts
        depends_on:
          - mlflow_db
          - minio
      mlflow_db:
        image: docker.io/bitnami/postgresql:latest
        environment:
          - POSTGRESQL_USERNAME=mlflow
          - POSTGRESQL_PASSWORD=mlflow123
          - POSTGRESQL_DATABASE=mlflow
      minio:
        image: docker.io/bitnami/minio:latest
        ports:
          - "9000:9000"
        environment:
          - MINIO_ROOT_USER=minio
          - MINIO_ROOT_PASSWORD=minio123
